version: '2.2'

services:

  zoo4:
    image: ${ZOOKEEPER_SERVER_IMAGE}
    #restart: always
    hostname: zoo4
    container_name: zoo4
    ports:
      - 2184:2181
    volumes:
      #- ${VOLUME_PATH}/conf/zoo.cfg:/conf/zoo.cfg
      - ${VOLUME_PATH}/zoo4/data:/data
      - ${VOLUME_PATH}/zoo4/datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo4:2888:3888 server.2=zoo5:2888:3888 server.3=zoo6:2888:3888
    networks:
      dnet:
        ipv4_address: 172.32.0.11

  zoo5:
    image: ${ZOOKEEPER_SERVER_IMAGE}
    #restart: always
    hostname: zoo5
    container_name: zoo5
    ports:
      - 2185:2181
    volumes:
      #- ${VOLUME_PATH}/conf/zoo.cfg:/conf/zoo.cfg
      - ${VOLUME_PATH}/zoo5/data:/data
      - ${VOLUME_PATH}/zoo5/datalog:/datalog
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo4:2888:3888 server.2=zoo5:2888:3888 server.3=zoo6:2888:3888
    networks:
      dnet:
        ipv4_address: 172.32.0.12

  zoo6:
    image: ${ZOOKEEPER_SERVER_IMAGE}
    #restart: always
    hostname: zoo6
    container_name: zoo6
    ports:
      - 2186:2181
    volumes:
      #- ${VOLUME_PATH}/conf/zoo.cfg:/conf/zoo.cfg
      - ${VOLUME_PATH}/zoo6/data:/data
      - ${VOLUME_PATH}/zoo6/datalog:/datalog
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo4:2888:3888 server.2=zoo5:2888:3888 server.3=zoo6:2888:3888
    networks:
      dnet:
        ipv4_address: 172.32.0.13

networks:
  dnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/16
          gateway: 172.32.0.1